[book]
title = "Palīgs būvkonstrukciju projektēšanā"
authors = ["N. Inovskis"]
language = "lv"
multilingual = false
src = "src"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/Inovskis/paligs-buvkonstrukciju-projektesana"
edit-url-template = "https://github.com/Inovskis/paligs-buvkonstrukciju-projektesana/edit/main/{path}"
additional-css = ["custom.css"]

[output.html.search]
enable = true
limit-results = 30
use-boolean-and = true
